In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("dataset_part_1.csv")

df.head()
df.isnull().sum()

FlightNumber        0
Date                0
BoosterVersion      0
PayloadMass        23
Orbit               1
LaunchSite          0
Outcome            24
Flights             0
GridFins            0
Reused              0
Legs                0
LandingPad        179
Block               0
ReusedCount       179
Serial              0
Longitude           0
Latitude            0
Class               0
dtype: int64

In [3]:
df["PayloadMass"] = df["PayloadMass"].fillna(df["PayloadMass"].mean())
df["Block"] = df["Block"].fillna(df["Block"].mode()[0] if not df["Block"].mode().empty else 0)
df["Flights"] = df["Flights"].fillna(1)
df["GridFins"] = df["GridFins"].fillna(False)
df["Reused"] = df["Reused"].fillna(False)
df["Legs"] = df["Legs"].fillna(False)

df["Date"] = pd.to_datetime(df["Date"])
df["Year"] = df["Date"].dt.year

In [4]:
features = df[[
    "FlightNumber",
    "PayloadMass",
    "Orbit",
    "LaunchSite",
    "Flights",
    "GridFins",
    "Reused",
    "Legs",
    "Block",
    "Longitude",
    "Latitude",
    "Class",
    "Year"
]]

features.head()

,FlightNumber,PayloadMass,Orbit,LaunchSite,Flights,GridFins,Reused,Legs,Block,Longitude,Latitude,Class,Year
0,6,8117.574038,LEO,CCSFS SLC 40,1,False,False,False,1,-80.577366,28.561857,0,2010
1,7,8117.574038,LEO,CCSFS SLC 40,1,False,False,False,1,-80.577366,28.561857,0,2010
2,8,525.000000,LEO,CCSFS SLC 40,1,False,False,False,1,-80.577366,28.561857,0,2012
3,9,400.000000,ISS,CCSFS SLC 40,1,False,False,False,1,-80.577366,28.561857,0,2012
4,10,677.000000,ISS,CCSFS SLC 40,1,False,False,False,1,-80.577366,28.561857,0,2013

In [5]:
features.to_csv("dataset_part_2.csv", index=False)